AWSTemplateFormatVersion: "2010-09-09"
Metadata:
  Generator: "console-recorder"
Description: ""
Resources:
  glued756d3d:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        ScriptLocation: "s3://aws-glue-script-location-786/CrossAccountGlueJob.scala"
      Name: CrossAccountGlueJob2
      Role: arn:aws:iam::341406773939:role/service-role/AWSGlueServiceRole-glueexecution786
      DefaultArguments:
        --TempDir: "s3://aws-glue-temporary-341406773939-us-east-1/kali7865164"
        --job-language: scala
        --class: CrossAccountGlueJob

