Mappings:
  RegionMap:
    us-east-1:
      HVM64: "ami-0ff323233"
      HVMG2: "ami-33222121"
    us-west-1:
      HVM64: "ami-322312"
      HVM62: "ami-2321312"
Resources:
  myEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: m1.small
